### ISSUE TITLE
Suggestion for data files section

### ISSUE THREAD

**Issue by informationista** [NCBI-Hackathons/SingleCellTranscriptEvidence#2]
This section states "For a selected list of organisms, pre-computed index files can be downloaded from here." A) is "here" supposed to be a link?  B) what organisms?

**Comment by DCGenomics** [comment]
Apparently, FTP links in md are not properly rendered.  

Ive taken out the shortcut and exposed the link

**Comment by vkkodali** [comment]
Thanks Ben, the link is fixed now.
